### ISSUE TITLE
location of requirements.txt in example-rundown could be explained more

### ISSUE THREAD

**Issue by secureray** [we45/ThreatPlaybook#13]
In https://we45.gitbook.io/threatplaybook/example-rundown where it says to: 

Install the Dependencies for the example with pip install -r requirements.txt 

It's not quite clear to me where that file comes from and what is in it.

If you don't mind explaining a little more about that file, it would be helpful.

**Comment by jsfan** [comment]
It looks like the docs are outdated on that part. There no longer seems to be a `requirements.txt` file because it has been replaces by a `Pipfile`/`Pipfile.lock` pair. Until the docs have been updated, have a look at https://pipenv.readthedocs.io/en/latest/ for instructions how to use `pipenv`.

**Comment by abhaybhargav** [comment]
Closing this issue as: 
* CLI is being updated to golang. No dependencies need to be installed
* Server functionality is being rewired to be a little easier to deploy
