### ISSUE TITLE
ThreatPlaybook docker graphQL Error

### ISSUE THREAD

**Issue by karthik137** [we45/ThreatPlaybook#25]
I am using docker setup.

I have tried to login using following credentials : 

username : "abhay@we45.com"
password : "pl@yb00k1234"

It logs in but shows a blank page. On console api throws graphql error.

Error message -->
```
api_1       | Traceback (most recent call last):
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executor.py", line 447, in resolve_or_error
api_1       |     return executor.execute(resolve_fn, source, info, **args)
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
api_1       |     return fn(*args, **kwargs)
api_1       |   File "/threatplaybook/gql.py", line 684, in resolve_projects
api_1       |     raise Exception("Unauthorized to perform action")
api_1       | Exception: Unauthorized to perform action
api_1       | ERROR: Traceback (most recent call last):
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executor.py", line 447, in resolve_or_error
api_1       |     return executor.execute(resolve_fn, source, info, **args)
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
api_1       |     return fn(*args, **kwargs)
api_1       |   File "/threatplaybook/gql.py", line 684, in resolve_projects
api_1       |     raise Exception("Unauthorized to perform action")
api_1       | graphql.error.located_error.GraphQLLocatedError: Unauthorized to perform action
```

**Comment by karthik137** [comment]
Looks like jwt token issue... Is the token correct in docker-compose file?.

**Comment by abhaybhargav** [comment]
I think you'll need to change password first and then login. In any case, we are working on a new release and new container image now. Should be done this week.

**Comment by karthik137** [comment]
How do i change the password?

**Comment by abhaybhargav** [comment]
You can find the instructions here: https://we45.github.io/ThreatPlaybook/#/Getting-Started/README

Sequence of events: 
1. Start ThreatPlaybook Server - with Docker-Compose
2. Download and install playbook client in a separate location `pip install ThreatPlaybook-Client` (py3)
3. Configure with CLI
4. Change-password with cli
5. login

We've changed some of the specs in the Docker-Compose and the overall product. Now, you'll have to run the docker-compose and change the default `superadmin` password that is set in the docker-compose with a CLI tool

You'll need py3 for the cli with `pip install ThreatPlaybook-Client`
