### ISSUE TITLE
Change the value of  VUE_APP_API_URL in docker-compose file

### ISSUE THREAD

**Issue by karthik137** [we45/ThreatPlaybook#26]
Please change it to "VUE_APP_API_URL=http://localhost:5042"

**Comment by abhaybhargav** [comment]
We are working on some changes to the Docker images in v 3.1. Should be done this week

**Comment by karthik137** [comment]
Ok.

**Comment by abhaybhargav** [comment]
This has been done. You'll need to use an addressable IP to access the Front-end or the API
