### ISSUE TITLE
ERROR: An error occurred while resolving field Query.projects

### ISSUE THREAD

**Issue by lareck** [we45/ThreatPlaybook#28]
I started the service using, "docker-compose up". Everything seems to download and install and the login page is presented. After logging in, the browser is redirected to, "http://127.0.0.1/home", which is blank.

The logs contain the following errors. Is this an environmental issue or an issue with the latest release?

api_1       | ERROR: An error occurred while resolving field Query.projects
api_1       | Traceback (most recent call last):
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executor.py", line 447, in resolve_or_error
api_1       |     return executor.execute(resolve_fn, source, info, **args)
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
api_1       |     return fn(*args, **kwargs)
api_1       |   File "/threatplaybook/gql.py", line 817, in resolve_projects
api_1       |     raise Exception("Unauthorized to perform action")
api_1       | Exception: Unauthorized to perform action
api_1       | ERROR: Traceback (most recent call last):
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executor.py", line 447, in resolve_or_error
api_1       |     return executor.execute(resolve_fn, source, info, **args)
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
api_1       |     return fn(*args, **kwargs)
api_1       |   File "/threatplaybook/gql.py", line 817, in resolve_projects
api_1       |     raise Exception("Unauthorized to perform action")
api_1       | graphql.error.located_error.GraphQLLocatedError: Unauthorized to perform action
api_1       | 
api_1       | ERROR: An error occurred while resolving field Query.userStories
api_1       | Traceback (most recent call last):
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executor.py", line 447, in resolve_or_error
api_1       |     return executor.execute(resolve_fn, source, info, **args)
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
api_1       |     return fn(*args, **kwargs)
api_1       |   File "/threatplaybook/gql.py", line 823, in resolve_user_stories
api_1       |     raise Exception("Unauthorized to perform action")
api_1       | Exception: Unauthorized to perform action
api_1       | ERROR: Traceback (most recent call last):
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executor.py", line 447, in resolve_or_error
api_1       |     return executor.execute(resolve_fn, source, info, **args)
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
api_1       |     return fn(*args, **kwargs)
api_1       |   File "/threatplaybook/gql.py", line 823, in resolve_user_stories
api_1       |     raise Exception("Unauthorized to perform action")
api_1       | graphql.error.located_error.GraphQLLocatedError: Unauthorized to perform action
api_1       | 
api_1       | ERROR: An error occurred while resolving field Query.scenarios
api_1       | Traceback (most recent call last):
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executor.py", line 447, in resolve_or_error
api_1       |     return executor.execute(resolve_fn, source, info, **args)
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
api_1       |     return fn(*args, **kwargs)
api_1       |   File "/threatplaybook/gql.py", line 829, in resolve_scenarios
api_1       |     raise Exception("Unauthorized to perform action")
api_1       | Exception: Unauthorized to perform action
api_1       | ERROR: Traceback (most recent call last):
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executor.py", line 447, in resolve_or_error
api_1       |     return executor.execute(resolve_fn, source, info, **args)
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
api_1       |     return fn(*args, **kwargs)
api_1       |   File "/threatplaybook/gql.py", line 829, in resolve_scenarios
api_1       |     raise Exception("Unauthorized to perform action")
api_1       | graphql.error.located_error.GraphQLLocatedError: Unauthorized to perform action
api_1       | 
api_1       | ERROR: An error occurred while resolving field Query.scans
api_1       | Traceback (most recent call last):
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executor.py", line 447, in resolve_or_error
api_1       |     return executor.execute(resolve_fn, source, info, **args)
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
api_1       |     return fn(*args, **kwargs)
api_1       |   File "/threatplaybook/gql.py", line 811, in resolve_scans
api_1       |     raise Exception("Unauthorized to perform action")
api_1       | Exception: Unauthorized to perform action
api_1       | ERROR: Traceback (most recent call last):
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executor.py", line 447, in resolve_or_error
api_1       |     return executor.execute(resolve_fn, source, info, **args)
api_1       |   File "/usr/local/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
api_1       |     return fn(*args, **kwargs)
api_1       |   File "/threatplaybook/gql.py", line 811, in resolve_scans
api_1       |     raise Exception("Unauthorized to perform action")
api_1       | graphql.error.located_error.GraphQLLocatedError: Unauthorized to perform action

**Comment by abhaybhargav** [comment]
Not sure if you've seen the docs: https://we45.github.io/ThreatPlaybook/#/Client/README

Once you run the docker compose, you'll need to change the default admin password (from the one given in your compose file) to something else and then login. Only after that you'll be able to perform any ops on the application 

you can do this with the client `playbook` or directly with the GraphQL API
