### ISSUE TITLE
ERROR while setting setting up the client - pip install pyjq failed on windows host

### ISSUE THREAD

**Issue by abhishekraghav** [we45/ThreatPlaybook#32]
Below is the stack trace on issuing docker-compose up command - 
--------------------------------------------------------------------------------
Creating threatplaybook_mongo_db_1 ... done
Creating threatplaybook_api_1      ... done
Creating threatplaybook_frontend_1 ... done
Creating threatplaybook_nginx_1    ... done
Attaching to threatplaybook_mongo_db_1, threatplaybook_api_1, threatplaybook_frontend_1, threatplaybook_nginx_1
frontend_1  | UPDATE AVAILABLE The latest version of `serve` is 11.3.0
frontend_1  | INFO: Accepting connections at http://localhost:8080
mongo_db_1  |  20:34:49.52
mongo_db_1  |  20:34:49.52 Welcome to the Bitnami mongodb container
mongo_db_1  |  20:34:49.53 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongo_db_1  |  20:34:49.53 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongo_db_1  |  20:34:49.54 Send us your feedback at containers@bitnami.com
mongo_db_1  |  20:34:49.54
mongo_db_1  |  20:34:49.54 INFO  ==> ** Starting MongoDB setup **
mongo_db_1  |  20:34:49.58 INFO  ==> Validating settings in MONGODB_* env vars...
mongo_db_1  |  20:34:49.68 INFO  ==> Initializing MongoDB...
mongo_db_1  |  20:34:49.69 INFO  ==> No injected configuration files found. Creating default config files...
mongo_db_1  |  20:34:50.09 INFO  ==> Enabling authentication...
mongo_db_1  |  20:34:50.10 INFO  ==> Deploying MongoDB with persisted data...
mongo_db_1  |  20:34:50.11 INFO  ==>
mongo_db_1  |  20:34:50.11 INFO  ==> ########################################################################
mongo_db_1  |  20:34:50.11 INFO  ==>  Installation parameters for MongoDB:
mongo_db_1  |  20:34:50.11 INFO  ==>    Persisted data and properties have been restored.
mongo_db_1  |  20:34:50.11 INFO  ==>    Any input specified will not take effect.
mongo_db_1  |  20:34:50.11 INFO  ==> (Passwords are not shown for security reasons)
mongo_db_1  |  20:34:50.11 INFO  ==> ########################################################################
mongo_db_1  |  20:34:50.11 INFO  ==>
mongo_db_1  |  20:34:50.12 INFO  ==> Loading custom scripts...
mongo_db_1  | find: '/docker-entrypoint-initdb.d/': No such file or directory
mongo_db_1  |
mongo_db_1  |  20:34:50.13 INFO  ==> ** MongoDB setup finished! **
mongo_db_1  |  20:34:50.15 INFO  ==> ** Starting MongoDB **
mongo_db_1  | 2020-04-05T20:34:50.173+0000 I CONTROL  [main] ***** SERVER RESTARTED *****
mongo_db_1  | 2020-04-05T20:34:50.175+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongo_db_1  | 2020-04-05T20:34:50.179+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/bitnami/mongodb/data/db 64-bit host=3ae65973d6cf
mongo_db_1  | 2020-04-05T20:34:50.179+0000 I CONTROL  [initandlisten] db version v4.0.14
mongo_db_1  | 2020-04-05T20:34:50.179+0000 I CONTROL  [initandlisten] git version: 1622021384533dade8b3c89ed3ecd80e1142c132
mongo_db_1  | 2020-04-05T20:34:50.179+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
mongo_db_1  | 2020-04-05T20:34:50.179+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_db_1  | 2020-04-05T20:34:50.179+0000 I CONTROL  [initandlisten] modules: none
mongo_db_1  | 2020-04-05T20:34:50.179+0000 I CONTROL  [initandlisten] build environment:
mongo_db_1  | 2020-04-05T20:34:50.179+0000 I CONTROL  [initandlisten]     distmod: debian92
mongo_db_1  | 2020-04-05T20:34:50.179+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongo_db_1  | 2020-04-05T20:34:50.179+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongo_db_1  | 2020-04-05T20:34:50.179+0000 I CONTROL  [initandlisten] options: { config: "/opt/bitnami/mongodb/conf/mongodb.conf", net: { bindIpAll: true, ipv6: false, port: 27017, unixDomainSocket: { enabled: true, pathPrefix: "/opt/bitnami/mongodb/tmp" } }, processManagement: { fork: false, pidFilePath: "/opt/bitnami/mongodb/tmp/mongodb.pid" }, security: { authorization: "enabled" }, setParameter: { enableLocalhostAuthBypass: "false" }, storage: { dbPath: "/bitnami/mongodb/data/db", directoryPerDB: false, journal: { enabled: true } }, systemLog: { destination: "file", logAppend: true, logRotate: "reopen", path: "/opt/bitnami/mongodb/logs/mongodb.log", quiet: false, verbosity: 0 } }
mongo_db_1  | 2020-04-05T20:34:50.186+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=470M,cache_overflow=(file_max=0M),session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
mongo_db_1  | 2020-04-05T20:34:50.743+0000 E STORAGE  [initandlisten] WiredTiger error (17) [1586118890:743268][1:0x7fe826cc2080], connection: __posix_open_file, 672: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: File exists Raw: [1586118890:743268][1:0x7fe826cc2080], connection: __posix_open_file, 672: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: File exists
mongo_db_1  | 2020-04-05T20:34:50.749+0000 I STORAGE  [initandlisten] WiredTiger message unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.3
mongo_db_1  | 2020-04-05T20:34:50.755+0000 E STORAGE  [initandlisten] WiredTiger error (1) [1586118890:755251][1:0x7fe826cc2080], connection: __posix_open_file, 672: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: Operation not permitted Raw: [1586118890:755251][1:0x7fe826cc2080], connection: __posix_open_file, 672: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: Operation not permitted
mongo_db_1  | 2020-04-05T20:34:50.780+0000 E STORAGE  [initandlisten] WiredTiger error (17) [1586118890:780456][1:0x7fe826cc2080], connection: __posix_open_file, 672: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: File exists Raw: [1586118890:780456][1:0x7fe826cc2080], connection: __posix_open_file, 672: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: File exists
mongo_db_1  | 2020-04-05T20:34:50.796+0000 I STORAGE  [initandlisten] WiredTiger message unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.4
mongo_db_1  | 2020-04-05T20:34:50.807+0000 E STORAGE  [initandlisten] WiredTiger error (1) [1586118890:806999][1:0x7fe826cc2080], connection: __posix_open_file, 672: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: Operation not permitted Raw: [1586118890:806999][1:0x7fe826cc2080], connection: __posix_open_file, 672: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: Operation not permitted
mongo_db_1  | 2020-04-05T20:34:50.833+0000 E STORAGE  [initandlisten] WiredTiger error (17) [1586118890:833557][1:0x7fe826cc2080], connection: __posix_open_file, 672: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: File exists Raw: [1586118890:833557][1:0x7fe826cc2080], connection: __posix_open_file, 672: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: File exists
mongo_db_1  | 2020-04-05T20:34:50.843+0000 I STORAGE  [initandlisten] WiredTiger message unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.5
mongo_db_1  | 2020-04-05T20:34:50.849+0000 E STORAGE  [initandlisten] WiredTiger error (1) [1586118890:849607][1:0x7fe826cc2080], connection: __posix_open_file, 672: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: Operation not permitted Raw: [1586118890:849607][1:0x7fe826cc2080], connection: __posix_open_file, 672: /bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: Operation not permitted
mongo_db_1  | 2020-04-05T20:34:50.852+0000 W STORAGE  [initandlisten] Failed to start up WiredTiger under any compatibility version.
mongo_db_1  | 2020-04-05T20:34:50.852+0000 F STORAGE  [initandlisten] Reason: 1: Operation not permitted
mongo_db_1  | 2020-04-05T20:34:50.852+0000 F -        [initandlisten] Fatal Assertion 28595 at src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp 707
mongo_db_1  | 2020-04-05T20:34:50.852+0000 F -        [initandlisten]
mongo_db_1  |
mongo_db_1  | ***aborting after fassert() failure
mongo_db_1  |
mongo_db_1  |
threatplaybook_mongo_db_1 exited with code 14

**Comment by abhishekraghav** [comment]
I got this working by using named volume. I modified the compose file a bit and it started working. Thanks.

**Comment by abhishekraghav** [comment]
@abhaybhargav can you please suggest. Thanks in advance.

**Comment by abhaybhargav** [comment]
Hi @abhishekraghav I will need some time to look at this issue. Currently, I have some client deliverables and will be unable to immediately resolve this. You might want to look at this, since it seems to be a software incompatibility with your OS

* https://github.com/doloopwhile/pyjq/issues/9
* https://github.com/doloopwhile/pyjq/issues/30

Looks like pyjq doesnt work in windows. So I will take this as a feature in the release I am currently working on and probably refrain from using pyjq

Will keep you posted and comment on this ticket when that happens. I expect that to be towards the end of this month.

**Comment by abhaybhargav** [comment]
Please watch this bug: https://github.com/we45/ThreatPlaybook/issues/33

**Comment by abhishekraghav** [comment]
Thank you so much @abhaybhargav . Looking forward to hear from you soon.

**Comment by abhaybhargav** [comment]
Launched 3.0.0 today. Considered closed as we have moved to golang CLI
