### ISSUE TITLE
Replace pyjq as it doesnt work with Windows OS for Playbook Client

### ISSUE THREAD

**Issue by abhaybhargav** [we45/ThreatPlaybook#33]

**Comment by abhaybhargav** [comment]
Not removing pyjq - Instead having users a Docker container to run the CLI. pyjq is very useful for the core functionality of the application. Will need to update a Dockerfile for this

**Comment by abhaybhargav** [comment]
Moved to Golang CLI, hence this is not an issue any more

**Comment by abhishekraghav** [comment]
Thanks @abhaybhargav .
