### ISSUE TITLE
Unable to change the default password for admin : playbook client returns error

### ISSUE THREAD

**Issue by abhishekraghav** [we45/ThreatPlaybook#34]
Hi @abhaybhargav 
I am able to  setup the server side components. While I try to setup the playbook client. 
I am able to do the first step i.e Playbook configure
But in the second step i.e changing the default password, I am failed to get through it. I am getting some JSONDecodeError. Not sure what's wrong here..
I have attached the error I am getting. 
I have also updated the JWT value in the compose file by the latest value.
![image](https://user-images.githubusercontent.com/19988460/79635235-6dc1a300-818d-11ea-9a0e-3b4c7a290853.png)

Thanks in advance.

**Comment by abhishekraghav** [comment]
Hi @abhaybhargav can you please suggest. I am kind of stuck here..
I did install insomnia and able to login with default credentials - Is there a direct API I can call to change the admin password instead of going through the Python route.
Thanks in advance.

**Comment by abhaybhargav** [comment]
You dont need to add any JWT value to the compose file.  The old password is the one in the compose file that needs to be changed. Not sure what is specifically wrong here as it works. 

Direct call is `POST` to `http://<server>:<port>/change-password`
with JSON Body
```json
{
	"email": "admin@admin.com",
	"old_password": "supersecret",
	"new_password": "somethingelse123",
	"verify_password": "somethingelse123"
}
```

**Comment by abhishekraghav** [comment]
@abhaybhargav 
Thanks for the input. I could change the default password of admin by calling the API instead.

![image](https://user-images.githubusercontent.com/19988460/79786256-c4cca100-8362-11ea-9cf8-85e4f53767b9.png)

Here i am able to login through API, but unable to still login through cli. Getting the same as before 
`[root@hostname]# playbook login
Please enter your email: admin@admin.com
Please enter your password:
Traceback (most recent call last):
  File "/usr/local/bin/playbook", line 11, in <module>
    load_entry_point('ThreatPlaybook-Client==3.1.3', 'console_scripts', 'playbook')()
  File "/usr/local/lib/python3.7/site-packages/playbook/__init__.py", line 660, in main
    if r.status_code == 200 and 'token' in r.json():
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

Not sure why python client is behaving differently. Is it something related to .cred file that gets generated on playbook configure..

**Comment by abhaybhargav** [comment]
Ah, I see. The old playbook client is python 2.7 and you have installed in a python 3.7 virtualenv. It should work if you reinstall it in a python 2.7.X virtualenv

Also - We are changing out the CLI and API to be more friendly in the new version - release to be EOM. Just FYI

**Comment by abhishekraghav** [comment]
Hi @abhaybhargav 

Thanks for the response.
As suggested by you, I have setup the python 2.7.X virtualenv. And reinstall the ThreatPlaybookClient. But again it is failed to work. Below is the error - 
![image](https://user-images.githubusercontent.com/19988460/80012957-bfe72900-84eb-11ea-85e2-93a869af1299.png)

Is there a workaround.

I hope this issue gets resolved in the upcoming release.

**Comment by abhishekraghav** [comment]
Hi @abhaybhargav 
I am able to resolve this issue. 
There is no issue in the python version and old client being used. 

Issue was in the playbook configure command. 
I was not passing the correct hostname of API server. I was providing the host IP address instead of docker IP(which I got once I did docker inspect).  Once I set the api server docker ip (i.e. 172.X.X.X), it started working fine.

It would be worth mentioning in the getting started page if somebody is trying to setup the server through docker way.
When can we expect the next version of Threat Playbook available to use and what are the new features coming up in the next release. If you can provide the sneak peak of it. That would be great.

Thanks.
