### ISSUE TITLE
ThreatPlaybook Client installation failed on Mac - "Running setup.py install for pyjq ... error"

### ISSUE THREAD

**Issue by vikrantkansal** [we45/ThreatPlaybook#35]
Hi,
I am facing issues while installing ThreatPlaybook Client on Mac machine Darwin-MacBook-Pro.local 19.4.0 Darwin Kernel Version 19.4.0 with Python 2.7.18 and pip 19.2.3
I have followed below steps
1. Install Python 2.7
2. Run pip install ThreatPlaybook-Client OR sudo -H pip install ThreatPlaybook-Client

setup failed on "pyjq" installation

ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5t/s_ltq5zs3s91srr2fkng2hzw0000gn/T/pip-install-0a7qlN/pyjq/setup.py'"'"'; __file__='"'"'/private/var/folders/5t/s_ltq5zs3s91srr2fkng2hzw0000gn/T/pip-install-0a7qlN/pyjq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/5t/s_ltq5zs3s91srr2fkng2hzw0000gn/T/pip-record-er5FZl/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

Please let me know if I have missed anything. I appreciate your help in resolving the issue.
Thanks so much!
[ThreatPlaybook_Error_Mac.TXT](https://github.com/we45/ThreatPlaybook/files/4521612/ThreatPlaybook_Error_Mac.TXT)

**Comment by abhishekraghav** [comment]
@vikrantkansal  I guess you might want to upgrade your python version to 3.6 or above. As the latest playbook client requires python 3.6 or above.

**Comment by vikrantkansal** [comment]
@abhishekraghav I have tried with python 3.6 and python 3.8. observed same error.

**Comment by abhaybhargav** [comment]
Hi @abhishekraghav and @vikrantkansal We've been working on updating the API, UI and the Client. Its quite a massive project and it should be done by May end. My apologies for the delay. Just to put this in perspective: 
* We are moving the API out of GraphQL as we were observing a lot of issues scaling it with GraphQL
* UI has been completely revamped to be more maintainable in the long run with Vuetify
* CLI is being rewritten in golang to make sure it works seamlessely and as a single binary without any hassles of installation,etc

Sorry about the issues you're facing. I want to make sure that you know that you're heard and we are addressing the issue. We have to maintain this OSS library outside of our day jobs and its a little hard to do especially at this time

**Comment by abhishekraghav** [comment]
@abhaybhargav  Thanks.
Looking forward to it. Hope it will get released by May end.

**Comment by abhishekraghav** [comment]
Hi @abhaybhargav When can we expect the next version of Threat Playbook...

**Comment by abhaybhargav** [comment]
@abhishekraghav we're nearly done. This friday is when we are looking to close all development on v3. 

The focus of this release is more stability than any changes/new features. New features will be built as and when we have time, incrementally

**Comment by abhishekraghav** [comment]
@abhaybhargav Thanks.
