### ISSUE TITLE
playbook init <project_name> does not create boilerplate directories (entities, results, security_tests)

### ISSUE THREAD

**Issue by abhishekraghav** [we45/ThreatPlaybook#36]
Hi @abhaybhargav 
The python client (playbook) doesn't create the boilerplate directories when I run below command.

`playbook init new_project`
It only creates cases folder. 
Below is the screen shot for the same. 

![image](https://user-images.githubusercontent.com/19988460/80710825-013f9000-8b0d-11ea-8953-1290f56f827e.png)

Please suggest. Do I have to install robot python packages.. 

Thanks.

**Comment by abhaybhargav** [comment]
Moved to new golang CLI. No need for all this anymore. Closing
