### ISSUE TITLE
Multiple CLI bugs

### ISSUE THREAD

**Issue by abhaybhargav** [we45/ThreatPlaybook#9]
* set `session` is not working
* get vulnerabilities in multiple formats

**Comment by jsfan** [comment]
@abhaybhargav Could you elaborate on the second point? I know you have assigned it to yourself but I might be able to have a look at this issue. However, while your first bullet point is clear, I'm not 100% sure what the second one is referring to.

**Comment by jsfan** [comment]
So, am I right to conclude that this issue as it stands is somewhat obsolete then?

**Comment by abhaybhargav** [comment]
Yes @jsfan. Please refer to the new [Rel2.0](https://github.com/we45/ThreatPlaybook/projects/2) project for the things I am planning for the new 2.0 release. 

Would love your contribs as always

**Comment by jsfan** [comment]
Cool. I'll have a look if there is anything of the right scope for me to help out with.
